"""Custom exceptions for data science workflows."""

from .base import DataScienceError
from .ingestion import (
    DataAugmentationError,
    DataFormatError,
    DataImbalanceError,
    DataLeakageError,
    DataLoadingError,
    DataNormalizationError,
    DataValidationError,
    FeatureEngineeringError,
    MissingDataError,
    OutlierDetectionError,
    SchemaMismatchError,
)
from .operations import (
    DataDriftError,
    DataExportError,
    DeploymentError,
    ResourceLimitError,
    SerializationError,
)
from .training import (
    BiasDetectionError,
    ConvergenceError,
    CrossValidationError,
    DimensionalityReductionError,
    EarlyStoppingError,
    ExperimentTrackingError,
    ExplainabilityError,
    FeatureScalingError,
    FeatureSelectionError,
    GPUOutOfMemoryError,
    HyperparameterError,
    HyperparameterTuningError,
    ModelCompatibilityError,
    ModelEvaluationError,
    ModelInferenceError,
    ModelTrainingError,
    OverfittingError,
    PredictionError,
    TrainingTimeoutError,
    UnderfittingError,
)

__all__ = [
    "DataScienceError",
    "DataLoadingError",
    "DataFormatError",
    "DataValidationError",
    "MissingDataError",
    "OutlierDetectionError",
    "SchemaMismatchError",
    "FeatureEngineeringError",
    "ModelTrainingError",
    "ConvergenceError",
    "TrainingTimeoutError",
    "HyperparameterError",
    "ModelEvaluationError",
    "PredictionError",
    "SerializationError",
    "DeploymentError",
    "DataDriftError",
    "ResourceLimitError",
    "DataExportError",
    "FeatureSelectionError",
    "DimensionalityReductionError",
    "CrossValidationError",
    "HyperparameterTuningError",
    "ExperimentTrackingError",
    "GPUOutOfMemoryError",
    "DataNormalizationError",
    "DataImbalanceError",
    "ModelInferenceError",
    "DataAugmentationError",
    "DataLeakageError",
    "OverfittingError",
    "UnderfittingError",
    "EarlyStoppingError",
    "BiasDetectionError",
    "ExplainabilityError",
    "FeatureScalingError",
    "ModelCompatibilityError",
]
